"""empty message

Revision ID: 6939021ed528
Revises: 5f754e0eb9f0
Create Date: 2025-07-18 17:36:49.241906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6939021ed528'
down_revision = '5f754e0eb9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
